export const ITEMS_RANKING_REQUEST = "ITEMS_RANKING_REQUEST";
export const ITEMS_RANKING_SUCCESS = "ITEMS_RANKING_SUCCESS";
export const ITEMS_RANKING_FAIL = "ITEMS_RANKING_FAIL";

export const ITEMS_INTERACTION_REQUEST = "ITEMS_INTERACTION_REQUEST";
export const ITEMS_INTERACTION_SUCCESS = "ITEMS_INTERACTION_SUCCESS";
export const ITEMS_INTERACTION_FAIL = "ITEMS_INTERACTION_FAIL";
